### ISSUE TITLE
Possible MOTD code or cheat code crash bug

### ISSUE THREAD

**Issue by AgustinJ879** [AHilyard/Prism#1]
Hi! i was having an issue with the last version of legendary tooltips that requires this mod... well the issue starts when i'm using an item with a custom color (MOTD Code/Cheat code) every time i try to kill a random mob it crashes i got forced to go back an old version of tooltips (that don't needed this mod) i hope this can be fix!

**Comment by AHilyard** [comment]
Hi, thanks for reporting this!  Would you be able to upload your latest.log file from when this happened?  It would be very helpful for me to be able to fix it.

**Comment by AgustinJ879** [comment]
Sadly since i have removed some mods and deleting the config folder it hasn't happened again (maybe was the old config)... sorry for wasting your time :(

**Comment by AHilyard** [comment]
Oh it's definitely not a waste of time.  I'll try some testing of my own to see if I can replicate it, thank you for bringing this to my attention.  I'll close this issue but if you manage to recreate it feel free to reopen.
