### ISSUE TITLE
Please update the mod to support 1.20

### ISSUE THREAD

**Issue by danielniccoli** [AHilyard/Prism#3]
Please update the mod to support 1.20

**Comment by ccrowles** [comment]
Seconded, our server won't update to 1.20.1 (not my choice) and the mod doesn't work with 1.20.

**Comment by AHilyard** [comment]
Thank you for your patience, Prism 1.0.5 has now been released which supports both 1.20 and 1.20.1.

**Comment by ccrowles** [comment]
Thanks!
